title: Project Documentation
description: Creative Technologies Master Documentation
theme: just-the-docs

url: https://sophiebunge.github.io/project-documentation/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
